name: Build Echo YouTube Extension APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      env:
        KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        echo "$KEYSTORE_B64" | base64 -d > ecoyoutubemusics.keystore
        echo "Keystore decoded successfully"
        ls -la ecoyoutubemusics.keystore

    - name: Build Debug APK
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        ./gradlew assembleDebug
        echo "Debug APK built successfully"

    - name: Build Release APK
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        ./gradlew assembleRelease
        echo "Release APK built successfully"

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: apk-files
        path: |
          app/build/outputs/apk/debug/*.apk
          app/build/outputs/apk/release/*.apk
        retention-days: 30

    - name: List build outputs
      run: |
        echo "=== APK Build Outputs ==="
        find app/build/outputs/apk -name "*.apk" -type f
        echo "=== Build Directory Structure ==="
        ls -la app/build/outputs/
